# Generated by Django 4.2.9 on 2026-03-04 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diagnostics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="afp",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="ca_125",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="ca_19_9",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="categorie_cancer",
            field=models.CharField(
                choices=[
                    ("solide", "Tumeur solide"),
                    ("liquide", "Tumeur liquide (hématologique)"),
                ],
                default="solide",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="cea",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="conf_biopsie_medullaire",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="conf_cytologie",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="conf_histologie_tumeur",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="conf_imagerie",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="conf_marqueurs_biologiques",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="conf_microscopie_sans_histo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="date_analyse_anapath",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="differentiation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="distance_marge_minimale",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="emboles_lymphatiques",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="emboles_vasculaires",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="etat_cancer",
            field=models.CharField(
                choices=[
                    ("localise", "Localisé"),
                    ("extension_regionale", "Extension régionale"),
                    ("metastatique", "Métastatique"),
                    ("non_determine", "Non déterminé"),
                ],
                default="non_determine",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="her2_fish",
            field=models.CharField(
                blank=True,
                choices=[
                    ("amplifie", "Amplifié"),
                    ("non_amplifie", "Non amplifié"),
                    ("non_fait", "Non fait"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="img_echographie",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="img_irm_cerebrale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="img_pet_scan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="img_radiographie",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="img_scanner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="img_scintigraphie",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="immunohistochimie",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="invasion_perineurale",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="invasion_vasculaire",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="laboratoire_anapath",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="marges_chirurgicales",
            field=models.CharField(
                blank=True,
                choices=[
                    ("r0", "Saines (R0)"),
                    ("r1", "Microscopiques (R1)"),
                    ("r2", "Macroscopiques (R2)"),
                    ("non_evaluables", "Non évaluables"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="medecin_anatomopathologiste",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="medecin_referent",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="methodes_confirmation_text",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="mmr_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deficient", "Déficient (dMMR)"),
                    ("proficient", "Proficient (pMMR)"),
                    ("inconnu", "Inconnu"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="modifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnostics_modifies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="nombre_ganglions_preleves",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="nombre_metastases",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="numero_dossier",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="pdl1",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="performance_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "PS 0 – Activité normale"),
                    ("1", "PS 1 – Symptômes, ambulatoire"),
                    ("2", "PS 2 – Alité <50% du temps"),
                    ("3", "PS 3 – Alité >50% du temps"),
                    ("4", "PS 4 – Invalide, alité"),
                    ("U", "Inconnu"),
                ],
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="pronostic_evaluation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("favorable", "Favorable"),
                    ("intermediaire", "Intermédiaire"),
                    ("defavorable", "Défavorable"),
                    ("inconnu", "Inconnu"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="qualite_prelevement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("adequate", "Adéquate"),
                    ("limite", "Limitée"),
                    ("inadequat", "Inadéquate"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="rapport_complet",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="recepteur_re_pourcentage",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="recepteur_rp_pourcentage",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="statut_dossier",
            field=models.CharField(
                choices=[
                    ("en_cours", "En cours"),
                    ("valide", "Validé"),
                    ("archive", "Archivé"),
                ],
                default="en_cours",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="taille_tumeur_3d",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="taille_tumeur_axe_max",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="technique_prelevement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("biopsie", "Biopsie"),
                    ("exerese_chirurgicale", "Exérèse chirurgicale"),
                    ("cytoponction", "Cytoponction"),
                    ("liquide_biologique", "Liquide biologique"),
                    ("autopsie", "Autopsie"),
                ],
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="tnm_certitude",
            field=models.CharField(
                blank=True,
                choices=[
                    ("certain", "Certain"),
                    ("probable", "Probable"),
                    ("suppose", "Supposé"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="tnm_commentaire",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="tnm_date_evaluation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="tnm_descripteurs",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="type_diagnostic",
            field=models.CharField(
                choices=[
                    ("initial", "Diagnostic initial"),
                    ("recidive", "Récidive"),
                    ("nouveau_primitif", "Nouveau primitif"),
                    ("metastase", "Métastase"),
                ],
                default="initial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="variante_histologique",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="volume_tumoral",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="diagnostic",
            name="est_principal",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="diagnostic",
            name="ki67",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="diagnostic",
            name="metastases_sites",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="diagnostic",
            name="psa",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="diagnostic",
            name="taille_tumeur",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=6, null=True
            ),
        ),
        migrations.CreateModel(
            name="StyleVie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut_tabagique",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("non_fumeur", "Non-fumeur"),
                            ("fumeur_actif", "Fumeur actif"),
                            ("ancien_fumeur", "Ancien fumeur"),
                            ("fumeur_passif", "Fumeur passif"),
                            ("inconnu", "Inconnu"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "paquets_annees",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "age_debut_tabac",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "age_arret_tabac",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("type_tabac", models.CharField(blank=True, max_length=100)),
                (
                    "nombre_cigarettes_jour",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "consommation_alcool",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("jamais", "Jamais"),
                            ("occasionnel", "Occasionnel (<1/semaine)"),
                            ("modere", "Modéré (1-7/semaine)"),
                            ("eleve", "Élevé (>7/semaine)"),
                            ("ancien_buveur", "Ancien buveur"),
                            ("inconnu", "Inconnu"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "unites_par_semaine",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("type_alcool", models.CharField(blank=True, max_length=100)),
                (
                    "duree_consommation_annees",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "niveau_activite",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sedentaire", "Sédentaire"),
                            ("leger", "Léger (<2h/sem)"),
                            ("modere", "Modéré (2-5h/sem)"),
                            ("intense", "Intense (>5h/sem)"),
                            ("inconnu", "Inconnu"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "heures_par_semaine",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("type_activite", models.CharField(blank=True, max_length=200)),
                ("frequence_activite", models.CharField(blank=True, max_length=50)),
                (
                    "poids",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "taille",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "imc",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "fruits_legumes_quotidien",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("alimentation_desc", models.TextField(blank=True)),
                ("regime_particulier", models.CharField(blank=True, max_length=100)),
                ("exposition_professionnelle", models.TextField(blank=True)),
                (
                    "duree_exposition_annees",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("profession", models.CharField(blank=True, max_length=150)),
                ("stress_chronique", models.BooleanField(blank=True, null=True)),
                (
                    "qualite_sommeil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bonne", "Bonne (7-9h)"),
                            ("insuffisante", "Insuffisante (<6h)"),
                            ("excessive", "Excessive (>10h)"),
                            ("troubles", "Troubles du sommeil"),
                            ("inconnu", "Inconnu"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "heures_sommeil",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "contraception_hormonale",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "allaitement_duree_mois",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "score_risque_global",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "diagnostic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_vie",
                        to="diagnostics.diagnostic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Style de vie",
                "db_table": "style_vie",
            },
        ),
    ]
