# Generated by Django 4.2.9 on 2026-04-14 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_diagnostic_hemopathie_maligne_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamensHematologiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siege_biopsie', models.TextField(blank=True, verbose_name='Siège Biopsie')),
                ('anapath', models.TextField(blank=True, verbose_name='Anapath')),
                ('immunohistochimie', models.TextField(blank=True, verbose_name='Immunohistochimie')),
                ('biopsie_osteomedulaire', models.TextField(blank=True, verbose_name='Biopsie ostéomédullaire')),
                ('myelogramme', models.TextField(blank=True, verbose_name='Myélogramme')),
                ('caryotype_medullaire', models.TextField(blank=True, verbose_name='Caryotype médullaire')),
                ('caryotype_fish_medullaire', models.TextField(blank=True, verbose_name='Caryotype / FISH médullaire')),
                ('fish_medullaire', models.TextField(blank=True, verbose_name='FISH médullaire')),
                ('cytochimie_medullaire', models.TextField(blank=True, verbose_name='Cytochimie médullaire')),
                ('cytogenetique_medullaire', models.TextField(blank=True, verbose_name='Cytogénétique médullaire')),
                ('coloration_perls', models.TextField(blank=True, verbose_name='Coloration de Perls')),
                ('nfs', models.TextField(blank=True, verbose_name='NFS')),
                ('frottis_sang', models.TextField(blank=True, verbose_name='Frottis de sang')),
                ('taux_lymphocytes', models.TextField(blank=True, verbose_name='Taux de lymphocytes')),
                ('taux_globules_blancs', models.TextField(blank=True, verbose_name='Taux de globules blancs')),
                ('cytometrie_flux', models.TextField(blank=True, verbose_name='Cytométrie en flux')),
                ('hemoglobine', models.TextField(blank=True, verbose_name='Hémoglobine')),
                ('biologie_moleculaire', models.TextField(blank=True, verbose_name='Biologie moléculaire')),
                ('electrophorese_proteines', models.TextField(blank=True, verbose_name='Électrophorèse des protéines')),
                ('immunofixation_sanguine', models.TextField(blank=True, verbose_name='Immunofixation sanguine')),
                ('free_light_chain', models.TextField(blank=True, verbose_name='Free Light Chain')),
                ('calcemie', models.TextField(blank=True, verbose_name='Calcémie')),
                ('clairance_renale', models.TextField(blank=True, verbose_name='Clairance rénale')),
                ('dosage_epo', models.TextField(blank=True, verbose_name="Dosage d'EPO")),
                ('radiologie_standard', models.TextField(blank=True, verbose_name='Radiologie standard')),
                ('irm', models.TextField(blank=True, verbose_name='IRM')),
                ('tdm_low_dose', models.TextField(blank=True, verbose_name='TDM low dose')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques complémentaires')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('diagnostic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examens_hemato', to='diagnostics.diagnostic')),
            ],
            options={
                'verbose_name': 'Examens hématologiques',
                'db_table': 'examens_hematologiques',
            },
        ),
    ]
