# Generated by Django 4.2.9 on 2026-05-22 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diagnostics", "0004_examenshematologiques"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diagnostic",
            name="examens_complementaires",
        ),
        migrations.RemoveField(
            model_name="diagnostic",
            name="hemopathie_maligne",
        ),
        migrations.DeleteModel(
            name="ExamensHematologiques",
        ),
    ]
