# Generated by Django 5.2.8 on 2026-02-26 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("diagnostics", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierRCP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordre_passage",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Ordre de présentation dans la réunion"
                    ),
                ),
                (
                    "type_presentation",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau dossier"),
                            ("recidive", "Récidive / Rechute"),
                            ("reval", "Réévaluation"),
                            ("post_trt", "Post-traitement"),
                            ("second", "Second avis"),
                            ("autre", "Autre"),
                        ],
                        default="nouveau",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("attente", "En attente"),
                            ("discute", "Discuté"),
                            ("reporte", "Reporté"),
                            ("annule", "Annulé"),
                        ],
                        default="attente",
                        max_length=20,
                    ),
                ),
                (
                    "resume_clinique",
                    models.TextField(
                        blank=True, help_text="Résumé du cas clinique présenté"
                    ),
                ),
                (
                    "question_posee",
                    models.TextField(
                        blank=True, help_text="Question clinique soumise à la RCP"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_rcp_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnostic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="diagnostics.diagnostic",
                    ),
                ),
                (
                    "medecin_presenteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_presentes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossiers_rcp",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier RCP",
                "db_table": "dossiers_rcp",
                "ordering": ["reunion", "ordre_passage"],
            },
        ),
        migrations.CreateModel(
            name="DecisionRCP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_decision",
                    models.CharField(
                        choices=[
                            ("chir", "Chirurgie"),
                            ("chimio", "Chimiothérapie"),
                            ("radio", "Radiothérapie"),
                            ("hormono", "Hormonothérapie"),
                            ("immuno", "Immunothérapie / Thérapie ciblée"),
                            ("radiochim", "Radiochimiothérapie concomitante"),
                            ("surveill", "Surveillance active"),
                            ("support", "Soins de support"),
                            ("palliatif", "Soins palliatifs"),
                            ("essai", "Inclusion essai clinique"),
                            ("second", "Demande second avis"),
                            ("bilan", "Bilan complémentaire"),
                            ("abstention", "Abstention thérapeutique"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("urgente", "Urgente (< 1 semaine)"),
                            ("rapide", "Rapide (< 1 mois)"),
                            ("normale", "Normale (1–3 mois)"),
                            ("differee", "Différée (> 3 mois)"),
                        ],
                        default="normale",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Détail de la décision thérapeutique"),
                ),
                (
                    "protocole",
                    models.CharField(
                        blank=True,
                        help_text="Protocole proposé ex: FOLFOX, AC-T",
                        max_length=200,
                    ),
                ),
                (
                    "delai_semaines",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Délai de mise en œuvre en semaines",
                        null=True,
                    ),
                ),
                (
                    "accord_patient",
                    models.BooleanField(
                        default=False, help_text="Accord du patient requis"
                    ),
                ),
                ("realise", models.BooleanField(default=False)),
                ("date_realisation", models.DateField(blank=True, null=True)),
                ("observations", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "medecin_referent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions_rcp_referentes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="rcp.dossierrcp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Décision RCP",
                "db_table": "decisions_rcp",
                "ordering": ["dossier", "type_decision"],
            },
        ),
        migrations.CreateModel(
            name="ReunionRCP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "type_rcp",
                    models.CharField(
                        choices=[
                            ("sein", "RCP Sein"),
                            ("digestif", "RCP Digestif"),
                            ("poumon", "RCP Thoracique / Poumon"),
                            ("orl", "RCP ORL / Tête & Cou"),
                            ("gyneco", "RCP Gynécologique"),
                            ("uro", "RCP Urologique"),
                            ("hemato", "RCP Hématologique"),
                            ("neuro", "RCP Neurologique"),
                            ("dermato", "RCP Dermatologique"),
                            ("os", "RCP Os / Tissus mous"),
                            ("pediatrique", "RCP Pédiatrique"),
                            ("palliative", "RCP Soins palliatifs"),
                            ("generale", "RCP Générale / Autre"),
                        ],
                        default="generale",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                            ("reportee", "Reportée"),
                        ],
                        default="planifiee",
                        max_length=20,
                    ),
                ),
                ("date_reunion", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField(blank=True, null=True)),
                ("lieu", models.CharField(blank=True, max_length=200)),
                ("salle", models.CharField(blank=True, max_length=100)),
                ("etablissement", models.CharField(blank=True, max_length=200)),
                (
                    "objectif",
                    models.TextField(
                        blank=True, help_text="Ordre du jour / objectifs de la réunion"
                    ),
                ),
                ("compte_rendu", models.TextField(blank=True)),
                ("observations", models.TextField(blank=True)),
                ("nombre_dossiers_prevus", models.PositiveSmallIntegerField(default=0)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "coordinateur",
                    models.ForeignKey(
                        blank=True,
                        help_text="Médecin coordinateur de la RCP",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rcps_coordonnees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rcps_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Réunion RCP",
                "verbose_name_plural": "Réunions RCP",
                "db_table": "reunions_rcp",
                "ordering": ["-date_reunion", "-heure_debut"],
            },
        ),
        migrations.AddField(
            model_name="dossierrcp",
            name="reunion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dossiers",
                to="rcp.reunionrcp",
            ),
        ),
        migrations.CreateModel(
            name="PresenceRCP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_externe",
                    models.CharField(
                        blank=True,
                        help_text="Médecin externe non inscrit",
                        max_length=150,
                    ),
                ),
                (
                    "specialite",
                    models.CharField(
                        choices=[
                            ("onco", "Oncologue médical"),
                            ("chir", "Chirurgien"),
                            ("radio", "Radiologue"),
                            ("radiot", "Radiothérapeute"),
                            ("anapath", "Anatomopathologiste"),
                            ("bio", "Biologiste"),
                            ("ref", "Médecin référent"),
                            ("psy", "Psychologue"),
                            ("inf", "Infirmier coordinateur"),
                            ("intern", "Interne / Résident"),
                            ("autre", "Autre"),
                        ],
                        default="onco",
                        max_length=20,
                    ),
                ),
                ("present", models.BooleanField(default=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Rôle spécifique dans cette RCP",
                        max_length=100,
                    ),
                ),
                (
                    "medecin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences_rcp",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reunion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to="rcp.reunionrcp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence RCP",
                "db_table": "presences_rcp",
                "unique_together": {("reunion", "medecin")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="dossierrcp",
            unique_together={("reunion", "patient")},
        ),
    ]
