# Generated by Django 4.2.9 on 2026-05-21 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rcp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionrcp",
            name="referentiel",
            field=models.CharField(
                blank=True, help_text="Source : INCa, NCCN, ESMO", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="decisionrcp",
            name="validee_par_coordinateur",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reunionrcp",
            name="code_acces",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="reunionrcp",
            name="est_virtuelle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reunionrcp",
            name="lien_visio",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="reunionrcp",
            name="secretaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rcps_secretariees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="decisionrcp",
            name="protocole",
            field=models.CharField(
                blank=True,
                help_text="Ex: FOLFOX, AC-T, Recommandations INCa",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="decisionrcp",
            name="realise",
            field=models.BooleanField(default=False, verbose_name="Traitement initié"),
        ),
        migrations.AlterField(
            model_name="reunionrcp",
            name="statut",
            field=models.CharField(
                choices=[
                    ("planifiee", "Planifiée"),
                    ("en_cours", "En cours"),
                    ("terminee", "Terminée"),
                    ("annulee", "Annulée"),
                    ("reportee", "Reportée"),
                    ("validee", "Validée & Archivée"),
                    ("suspendue", "Suspendue"),
                ],
                default="planifiee",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MessageRCP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("est_important", models.BooleanField(default=False)),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussions",
                        to="rcp.dossierrcp",
                    ),
                ),
                (
                    "reunion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="rcp.reunionrcp",
                    ),
                ),
            ],
            options={
                "db_table": "rcp_messages",
                "ordering": ["date_envoi"],
            },
        ),
    ]
