# Generated by Django 4.2.9 on 2026-05-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rcp", "0004_decisionrcp_referentiel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decisionrcp",
            name="referentiel",
        ),
        migrations.RemoveField(
            model_name="decisionrcp",
            name="validee_par_coordinateur",
        ),
        migrations.RemoveField(
            model_name="reunionrcp",
            name="code_acces",
        ),
        migrations.RemoveField(
            model_name="reunionrcp",
            name="est_virtuelle",
        ),
        migrations.RemoveField(
            model_name="reunionrcp",
            name="lien_visio",
        ),
        migrations.RemoveField(
            model_name="reunionrcp",
            name="secretaire",
        ),
        migrations.AlterField(
            model_name="decisionrcp",
            name="protocole",
            field=models.CharField(
                blank=True,
                help_text="Protocole proposé ex: FOLFOX, AC-T",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="decisionrcp",
            name="realise",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reunionrcp",
            name="statut",
            field=models.CharField(
                choices=[
                    ("planifiee", "Planifiée"),
                    ("en_cours", "En cours"),
                    ("terminee", "Terminée"),
                    ("annulee", "Annulée"),
                    ("reportee", "Reportée"),
                ],
                default="planifiee",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="MessageRCP",
        ),
    ]
