# Generated by Django 4.2.9 on 2026-05-22 22:57

import apps.rcp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rcp", "0005_remove_decisionrcp_referentiel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageRCP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("est_important", models.BooleanField(default=False)),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_rcp",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussions",
                        to="rcp.dossierrcp",
                    ),
                ),
                (
                    "reunion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="rcp.reunionrcp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message RCP",
                "db_table": "rcp_messages",
                "ordering": ["date_envoi"],
            },
        ),
        migrations.CreateModel(
            name="FichierDossierRCP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(upload_to=apps.rcp.models.upload_to_dossier),
                ),
                ("nom_original", models.CharField(blank=True, max_length=255)),
                (
                    "type_fichier",
                    models.CharField(
                        choices=[
                            ("dicom", "Image DICOM"),
                            ("scanner", "Scanner / TDM"),
                            ("irm", "IRM"),
                            ("radio", "Radiographie"),
                            ("echo", "Echographie"),
                            ("anapath", "Anatomopathologie"),
                            ("biologie", "Bilan biologique"),
                            ("autre", "Autre document"),
                        ],
                        default="autre",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                ("taille_bytes", models.PositiveIntegerField(blank=True, null=True)),
                ("date_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fichiers",
                        to="rcp.dossierrcp",
                    ),
                ),
                (
                    "uploade_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fichier dossier RCP",
                "db_table": "fichiers_dossier_rcp",
                "ordering": ["-date_upload"],
            },
        ),
    ]
