# Generated by Django 4.2.9 on 2026-05-23 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rcp_invite", "Invitation à une RCP"),
                            ("rcp_demarre", "Réunion démarrée"),
                            ("rcp_terminee", "Réunion terminée"),
                            ("nouveau_msg", "Nouveau message"),
                            ("new_decision", "Nouvelle décision"),
                            ("dossier_ajoute", "Dossier ajouté"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True)),
                ("lue", models.BooleanField(default=False)),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                ("reunion_id", models.IntegerField(blank=True, null=True)),
                ("dossier_id", models.IntegerField(blank=True, null=True)),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "db_table": "notifications",
                "ordering": ["-date_envoi"],
            },
        ),
    ]
