# Generated by Django 4.2.9 on 2026-09-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('rcp_invite', 'Invitation à une RCP'), ('rcp_demarre', 'Réunion démarrée'), ('rcp_terminee', 'Réunion terminée'), ('nouveau_msg', 'Nouveau message'), ('new_decision', 'Nouvelle décision'), ('dossier_ajoute', 'Dossier ajouté'), ('rdv_waitlist', 'Créneau liste d’attente')], max_length=30),
        ),
    ]
