# Generated by Django 4.2.9 on 2026-03-01 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0002_remove_patient_nom_jeune_fille_and_more"),
        ("suivi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationsuivi",
            name="activite_physique",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedentaire", "Sédentaire"),
                    ("leger", "Activité légère"),
                    ("modere", "Activité modérée"),
                    ("intense", "Activité intense"),
                    ("inconnu", "Inconnu"),
                ],
                default="inconnu",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="consultationsuivi",
            name="alcool",
            field=models.CharField(
                blank=True,
                choices=[("non", "Non"), ("oui", "Oui"), ("inconnu", "Inconnu")],
                default="inconnu",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="consultationsuivi",
            name="alimentation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equilibree", "Équilibrée"),
                    ("desequilibree", "Déséquilibrée"),
                    ("inconnu", "Inconnu"),
                ],
                default="inconnu",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="consultationsuivi",
            name="date_dernier_rdv",
            field=models.DateField(
                blank=True, help_text="Date du dernier rendez-vous effectif", null=True
            ),
        ),
        migrations.AddField(
            model_name="consultationsuivi",
            name="date_derniere_rechute",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationsuivi",
            name="exposition_toxique",
            field=models.BooleanField(
                default=False,
                help_text="Exposition à des substances toxiques (travail, environnement)",
            ),
        ),
        migrations.AddField(
            model_name="consultationsuivi",
            name="exposition_toxique_detail",
            field=models.CharField(
                blank=True, help_text="Préciser le type d'exposition", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="consultationsuivi",
            name="nombre_rechutes",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Nombre total de rechutes"
            ),
        ),
        migrations.AddField(
            model_name="consultationsuivi",
            name="pathologies_chroniques",
            field=models.TextField(
                blank=True, help_text="Ex: Diabète type 2, HTA, Insuffisance rénale..."
            ),
        ),
        migrations.AddField(
            model_name="consultationsuivi",
            name="rechute",
            field=models.BooleanField(
                default=False, help_text="Le patient a-t-il eu une rechute ?"
            ),
        ),
        migrations.AddField(
            model_name="consultationsuivi",
            name="tabac",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non", "Non-fumeur"),
                    ("ex", "Ex-fumeur"),
                    ("actif", "Fumeur actif"),
                    ("inconnu", "Inconnu"),
                ],
                default="inconnu",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="consultationsuivi",
            name="tabac_paquets_annee",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Nombre de paquets-années",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evenementclinique",
            name="lien_traitement",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="evenementclinique",
            name="traitement_consequence",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="qualitevie",
            name="score_global_sante",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Score global santé / QdV de 1 à 7", null=True
            ),
        ),
        migrations.CreateModel(
            name="EffetIndesirable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicament_cause",
                    models.CharField(
                        help_text="Médicament ou traitement en cause (ex: Docetaxel, Radiothérapie...)",
                        max_length=200,
                    ),
                ),
                (
                    "type_effet",
                    models.CharField(
                        choices=[
                            ("hemato", "Hématologique (anémie, neutropénie...)"),
                            (
                                "digestif",
                                "Digestif (nausées, vomissements, diarrhée...)",
                            ),
                            ("cutane", "Cutané (rash, alopécie...)"),
                            ("neuro", "Neurologique (neuropathie...)"),
                            ("cardiaque", "Cardiaque (cardiotoxicité...)"),
                            ("hepatique", "Hépatique (cytolyse...)"),
                            ("renal", "Rénal (néphrotoxicité...)"),
                            ("pulmo", "Pulmonaire (pneumopathie...)"),
                            ("fatigue", "Fatigue / Asthénie"),
                            ("douleur", "Douleur"),
                            ("psycho", "Psychologique (anxiété, dépression...)"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description détaillée de l'effet indésirable"
                    ),
                ),
                (
                    "severite",
                    models.CharField(
                        choices=[
                            ("1", "Grade 1 – Léger (asymptomatique)"),
                            ("2", "Grade 2 – Modéré (intervention minimale)"),
                            ("3", "Grade 3 – Sévère (hospitalisation)"),
                            ("4", "Grade 4 – Critique (pronostic vital)"),
                            ("5", "Grade 5 – Décès"),
                        ],
                        max_length=1,
                    ),
                ),
                ("date_apparition", models.DateField()),
                ("date_resolution", models.DateField(blank=True, null=True)),
                ("resolu", models.BooleanField(default=False)),
                (
                    "impact_traitement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("aucun", "Aucun impact"),
                            ("reduction_dose", "Réduction de dose"),
                            ("report", "Report du traitement"),
                            ("arret_temp", "Arrêt temporaire"),
                            ("arret_def", "Arrêt définitif"),
                            ("inconnu", "Non documenté"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "traitement_symptomatique",
                    models.TextField(
                        blank=True,
                        help_text="Traitement mis en place pour gérer l'effet",
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="effets_indesirables",
                        to="suivi.consultationsuivi",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="effets_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effets_indesirables",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Effet indésirable",
                "verbose_name_plural": "Effets indésirables",
                "db_table": "effets_indesirables",
                "ordering": ["-date_apparition"],
            },
        ),
    ]
