# Generated by Django 4.2.9 on 2026-09-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0005_rendezvouswaitlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RendezVousWaitlist',
        ),
    ]
