# Generated by Django 4.2.9 on 2026-03-01 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CancerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("label", models.CharField(max_length=200)),
                ("categorie", models.CharField(blank=True, max_length=100)),
                ("icd_codes", models.JSONField(blank=True, default=list)),
                ("est_actif", models.BooleanField(default=True)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Type de cancer",
                "verbose_name_plural": "Types de cancer",
                "db_table": "stats_cancer_type",
                "ordering": ["ordre", "label"],
            },
        ),
        migrations.CreateModel(
            name="Wilaya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=50)),
                ("population", models.PositiveIntegerField(default=0)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Wilaya",
                "verbose_name_plural": "Wilayas",
                "db_table": "stats_wilaya",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("results_count", models.PositiveSmallIntegerField(default=0)),
                ("source", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de recherche",
                "verbose_name_plural": "Logs de recherche",
                "db_table": "stats_search_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("running", "En cours"),
                            ("done", "Terminé"),
                            ("error", "Erreur"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("contenu_md", models.TextField(blank=True)),
                ("recommandations", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport IA",
                "verbose_name_plural": "Rapports IA",
                "db_table": "stats_ai_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurvivalRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stade",
                    models.CharField(
                        choices=[
                            ("I", "Stade I"),
                            ("II", "Stade II"),
                            ("III", "Stade III"),
                            ("IV", "Stade IV"),
                            ("ALL", "Tous stades"),
                        ],
                        default="ALL",
                        max_length=5,
                    ),
                ),
                ("annee_ref", models.PositiveSmallIntegerField()),
                ("groupe_age", models.CharField(blank=True, max_length=20)),
                ("sexe", models.CharField(blank=True, max_length=10)),
                ("survie_1an", models.FloatField(default=0.0)),
                ("survie_3ans", models.FloatField(default=0.0)),
                ("survie_5ans", models.FloatField(default=0.0)),
                ("n_patients", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancer_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survival_rates",
                        to="stats.cancertype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taux de survie",
                "verbose_name_plural": "Taux de survie",
                "db_table": "stats_survival_rate",
                "ordering": ["-annee_ref", "cancer_type", "stade"],
                "unique_together": {
                    ("cancer_type", "annee_ref", "stade", "groupe_age", "sexe")
                },
            },
        ),
        migrations.CreateModel(
            name="IncidenceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveSmallIntegerField()),
                (
                    "mois",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1-12, null = données annuelles",
                        null=True,
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Homme"), ("F", "Femme"), ("T", "Tous")],
                        default="T",
                        max_length=1,
                    ),
                ),
                (
                    "tranche_age",
                    models.CharField(
                        blank=True, help_text="ex: 40-49, 50-59, 60+", max_length=20
                    ),
                ),
                (
                    "stade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Stade I"),
                            ("II", "Stade II"),
                            ("III", "Stade III"),
                            ("IV", "Stade IV"),
                            ("INC", "Inconnu"),
                        ],
                        max_length=5,
                    ),
                ),
                ("nb_cas", models.PositiveIntegerField(default=0)),
                ("nb_deces", models.PositiveIntegerField(default=0)),
                (
                    "taux_brut",
                    models.FloatField(default=0.0, help_text="Pour 100 000 habitants"),
                ),
                (
                    "taux_std",
                    models.FloatField(default=0.0, help_text="Taux standardisé monde"),
                ),
                ("population", models.PositiveIntegerField(default=0)),
                (
                    "cancer_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidence_records",
                        to="stats.cancertype",
                    ),
                ),
                (
                    "wilaya",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidence_records",
                        to="stats.wilaya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enregistrement d'incidence",
                "verbose_name_plural": "Enregistrements d'incidence",
                "db_table": "stats_incidence_record",
                "ordering": ["-annee", "-mois", "cancer_type"],
                "unique_together": {
                    (
                        "cancer_type",
                        "wilaya",
                        "annee",
                        "mois",
                        "sexe",
                        "tranche_age",
                        "stade",
                    )
                },
            },
        ),
    ]
