# Generated by Django 4.2.9 on 2026-05-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aireport",
            name="charts_json",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
