# Generated by Django 4.2.9 on 2026-05-22 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0002_aireport_charts_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aireport",
            name="charts_json",
        ),
    ]
