# Generated by Django 5.2.8 on 2026-02-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="nom_jeune_fille",
        ),
        migrations.AddField(
            model_name="patient",
            name="activite_physique",
            field=models.CharField(
                choices=[
                    ("sedentaire", "Sédentaire"),
                    ("moderee", "Modérée"),
                    ("active", "Active"),
                    ("inconnu", "Inconnu"),
                ],
                default="inconnu",
                max_length=20,
                verbose_name="Activité physique",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="alimentation",
            field=models.CharField(
                choices=[
                    ("equilibree", "Équilibrée"),
                    ("grasse", "Riche en graisses"),
                    ("sucree", "Riche en sucres"),
                    ("vegetarienne", "Végétarienne/Végane"),
                    ("inconnu", "Inconnu"),
                ],
                default="inconnu",
                max_length=50,
                verbose_name="Alimentation",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="num_securite_sociale",
            field=models.CharField(
                blank=True,
                help_text="Numéro de sécurité sociale / assurance maladie",
                max_length=30,
                verbose_name="N° sécurité sociale",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sexe",
            field=models.CharField(
                choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
            ),
        ),
    ]
