# Generated by Django 4.2.9 on 2026-03-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_nom_jeune_fille_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nom_jeune_fille',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom de jeune fille'),
        ),
        migrations.AddField(
            model_name='patient',
            name='num_matricule',
            field=models.CharField(blank=True, help_text='Numéro de matricule', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='service_clinique',
            field=models.CharField(blank=True, help_text="Service ou clinique d'origine", max_length=200),
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tension_arterielle', models.CharField(blank=True, max_length=20)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pouls', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('glycemie', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taille_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('acte_chirurgical', models.TextField(blank=True)),
                ('actes_par_pathologie', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('bilan_psychologique', models.TextField(blank=True)),
                ('dossier_crypte', models.BooleanField(default=False)),
                ('localisation_tumorale', models.CharField(blank=True, choices=[('1', 'Local'), ('2', 'Locorégional'), ('3', 'Métastase'), ('4', 'Indéterminé')], max_length=1)),
                ('suivi', models.CharField(blank=True, choices=[('1', 'Vivant'), ('2', 'Décédé'), ('3', 'Perdu de vue')], max_length=1)),
                ('date_deces', models.DateField(blank=True, null=True)),
                ('cause_deces', models.CharField(blank=True, max_length=200)),
                ('date_derniere_consultation', models.DateField(blank=True, null=True)),
                ('medecin_traitant', models.CharField(blank=True, max_length=150)),
                ('base_diagnostic', models.CharField(blank=True, choices=[('1', 'Anatomopathologie primitive'), ('2', 'Cytologie/examen cellulaire'), ('3', 'Anatomopathologie métastase'), ('4', 'Clinique ou imagerie')], max_length=1)),
                ('marqueurs_tumoraux', models.TextField(blank=True)),
                ('premier_examen_anapath_positif', models.DateField(blank=True, null=True)),
                ('type_grade_histologique', models.CharField(blank=True, max_length=100)),
                ('stade_diagnostic', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Dossier Médical',
                'verbose_name_plural': 'Dossiers Médicaux',
                'db_table': 'dossier_medical',
            },
        ),
    ]
