# Generated by Django 5.2.8 on 2026-03-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("doctor", "Médecin Oncologue"),
                    ("anapath", "Médecin Anapath"),
                    ("epidemiologist", "Épidémiologiste"),
                    ("readonly", "Lecture seule"),
                ],
                default="readonly",
                max_length=20,
            ),
        ),
    ]
