<<<<<<< HEAD
# Generated by Django 4.2.9 on 2026-05-12 17:29
=======
# Generated by Django 4.2.9 on 2026-04-14 21:36
>>>>>>> 0997e3a77655b6b374b3415fca2675beffe4b0ad

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_anapath_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
