# Generated by Django 4.2.9 on 2026-09-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_consultation_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('doctor', 'Médecin Oncologue'), ('anapath', 'Médecin Anapath'), ('epidemiologist', 'Épidémiologiste'), ('pharmacist', 'Pharmacien'), ('readonly', 'Lecture seule'), ('secretaire', 'Saise des données'), ('doctor_chef', 'Médecin Chef')], default='readonly', max_length=20),
        ),
    ]
