# Generated by Django 4.2.9 on 2026-03-03 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChampPersonnalise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(help_text="Nom du champ affiché", max_length=100),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Identifiant interne (généré auto)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description / aide pour le médecin"
                    ),
                ),
                (
                    "type_champ",
                    models.CharField(
                        choices=[
                            ("texte", "Texte libre"),
                            ("nombre", "Nombre"),
                            ("date", "Date"),
                            ("booleen", "Oui / Non"),
                            ("textarea", "Texte long"),
                            ("select", "Liste déroulante"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("patient", "Dossier patient"),
                            ("diagnostic", "Diagnostic"),
                            ("traitement", "Traitement"),
                            ("suivi", "Suivi / Consultation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "topographie_code",
                    models.CharField(
                        blank=True,
                        help_text="Code ICD-O-3 si spécifique à un cancer (ex: C50 pour sein). Vide = global.",
                        max_length=10,
                    ),
                ),
                ("topographie_libelle", models.CharField(blank=True, max_length=100)),
                (
                    "options_json",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text='Options pour liste déroulante — JSON array ex: ["Option1","Option2"]',
                    ),
                ),
                ("obligatoire", models.BooleanField(default=False)),
                ("actif", models.BooleanField(default=True)),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordre d'affichage"
                    ),
                ),
                ("valeur_min", models.FloatField(blank=True, null=True)),
                ("valeur_max", models.FloatField(blank=True, null=True)),
                (
                    "unite",
                    models.CharField(
                        blank=True, help_text="Unité ex: mg/L, cm, %", max_length=20
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="champs_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Champ personnalisé",
                "verbose_name_plural": "Champs personnalisés",
                "db_table": "custom_fields_definition",
                "ordering": ["module", "ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="ValeurChamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=20)),
                ("object_id", models.PositiveIntegerField()),
                ("valeur", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "champ",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valeurs",
                        to="custom_fields.champpersonnalise",
                    ),
                ),
                (
                    "saisi_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Valeur champ personnalisé",
                "db_table": "custom_fields_values",
                "unique_together": {("champ", "module", "object_id")},
            },
        ),
    ]
