# Generated by Django 5.2.12 on 2026-04-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_fields", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="champpersonnalise",
            name="topographie_code",
            field=models.CharField(
                blank=True,
                help_text="Code(s) ICD-O-3 si spécifique à un/plusieurs cancer(s) (ex: C50 ou C50,C18). Vide = global.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="champpersonnalise",
            name="topographie_libelle",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
