# Generated by Django 4.2.9 on 2026-03-04 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wilaya",
            fields=[
                (
                    "code",
                    models.PositiveSmallIntegerField(
                        help_text="Numéro officiel de la wilaya (1–58)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom officiel de la wilaya", max_length=100
                    ),
                ),
                (
                    "nom_ar",
                    models.CharField(
                        blank=True, help_text="Nom en arabe", max_length=100
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("nord", "Nord (Littoral)"),
                            ("est", "Est"),
                            ("ouest", "Ouest"),
                            ("hauts_plateaux", "Hauts Plateaux"),
                            ("sud", "Grand Sud"),
                        ],
                        db_index=True,
                        default="nord",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude du chef-lieu",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude du chef-lieu",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "superficie_km2",
                    models.PositiveIntegerField(
                        blank=True, help_text="Superficie en km²", null=True
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Population (dernier recensement)",
                        null=True,
                    ),
                ),
                ("chef_lieu", models.CharField(blank=True, max_length=100)),
                ("nb_communes", models.PositiveSmallIntegerField(default=0)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wilaya",
                "verbose_name_plural": "Wilayas",
                "db_table": "sig_wilayas",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FacteurRisque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "portee",
                    models.CharField(
                        choices=[
                            ("wilaya", "Spécifique à une wilaya"),
                            ("region", "Spécifique à une région"),
                            ("national", "National"),
                        ],
                        default="region",
                        max_length=10,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nord", "Nord (Littoral)"),
                            ("est", "Est"),
                            ("ouest", "Ouest"),
                            ("hauts_plateaux", "Hauts Plateaux"),
                            ("sud", "Grand Sud"),
                        ],
                        help_text="Région concernée (si portée = région)",
                        max_length=20,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom du facteur de risque", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("tres_eleve", "Très élevé"),
                            ("eleve", "Élevé"),
                            ("modere", "Modéré"),
                            ("faible", "Faible"),
                        ],
                        default="modere",
                        max_length=15,
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Emoji représentant le facteur (ex: 🚬)",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source épidémiologique (INSP, OMS, INCa…)",
                        max_length=200,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Ordre d'affichage (0 = premier)"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "wilaya",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide pour un facteur régional/national",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facteurs_risque",
                        to="sig.wilaya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facteur de risque",
                "verbose_name_plural": "Facteurs de risque",
                "db_table": "sig_facteurs_risque",
                "ordering": ["ordre", "niveau", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code commune (ex: 16001)", max_length=10
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("nom_ar", models.CharField(blank=True, max_length=150)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("population", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "est_chef_lieu",
                    models.BooleanField(
                        default=False,
                        help_text="Cette commune est-elle le chef-lieu de la wilaya ?",
                    ),
                ),
                (
                    "wilaya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communes",
                        to="sig.wilaya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commune",
                "db_table": "sig_communes",
                "ordering": ["wilaya", "nom"],
                "unique_together": {("wilaya", "code")},
            },
        ),
        migrations.CreateModel(
            name="AlerteEpidemiologique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("vigilance", "Vigilance"),
                            ("alerte", "Alerte"),
                            ("urgence", "Urgence"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "type_cancer",
                    models.CharField(
                        blank=True,
                        help_text="Type de cancer concerné (vide = tous types)",
                        max_length=100,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes_sig_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wilaya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes",
                        to="sig.wilaya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte épidémiologique",
                "verbose_name_plural": "Alertes épidémiologiques",
                "db_table": "sig_alertes",
                "ordering": ["-date_debut", "niveau"],
            },
        ),
        migrations.CreateModel(
            name="StatCancerWilaya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee",
                    models.PositiveSmallIntegerField(
                        db_index=True, help_text="Année de la statistique"
                    ),
                ),
                ("total_patients", models.PositiveIntegerField(default=0)),
                ("total_hommes", models.PositiveIntegerField(default=0)),
                ("total_femmes", models.PositiveIntegerField(default=0)),
                (
                    "total_nouveaux",
                    models.PositiveIntegerField(
                        default=0, help_text="Nouveaux cas diagnostiqués cette année"
                    ),
                ),
                ("total_deces", models.PositiveIntegerField(default=0)),
                (
                    "incidence_pour_100k",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Taux pour 100 000 habitants",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "cancers_json",
                    models.JSONField(
                        default=dict, help_text='{"Sein": 45, "Colorectal": 23, …}'
                    ),
                ),
                (
                    "communes_json",
                    models.JSONField(
                        default=list,
                        help_text='[{"nom": "Oran", "total": 45, "cancers": {…}}, …]',
                    ),
                ),
                (
                    "date_calcul",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date/heure du dernier calcul",
                    ),
                ),
                (
                    "est_complet",
                    models.BooleanField(
                        default=False,
                        help_text="True si le calcul a été effectué sans erreur",
                    ),
                ),
                (
                    "wilaya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats_cancer",
                        to="sig.wilaya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistique wilaya",
                "verbose_name_plural": "Statistiques par wilaya",
                "db_table": "sig_stats_wilaya",
                "ordering": ["-annee", "wilaya"],
                "unique_together": {("wilaya", "annee")},
            },
        ),
        migrations.CreateModel(
            name="StatCancerCommune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveSmallIntegerField(db_index=True)),
                ("total_patients", models.PositiveIntegerField(default=0)),
                ("cancers_json", models.JSONField(default=dict)),
                (
                    "date_calcul",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats_cancer",
                        to="sig.commune",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistique commune",
                "verbose_name_plural": "Statistiques par commune",
                "db_table": "sig_stats_commune",
                "ordering": ["-annee", "commune"],
                "unique_together": {("commune", "annee")},
            },
        ),
    ]
