# Generated by Django 4.2.9 on 2026-03-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('annee', models.PositiveSmallIntegerField()),
                ('population', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Population Commune',
                'verbose_name_plural': 'Populations Communes',
                'db_table': 'sig_population_commune',
                'ordering': ['wilaya', 'commune', 'annee'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commune',
            name='wilaya',
        ),
        migrations.RemoveField(
            model_name='facteurrisque',
            name='wilaya',
        ),
        migrations.AlterUniqueTogether(
            name='statcancercommune',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='statcancercommune',
            name='commune',
        ),
        migrations.AlterUniqueTogether(
            name='statcancerwilaya',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='statcancerwilaya',
            name='wilaya',
        ),
        migrations.DeleteModel(
            name='AlerteEpidemiologique',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='FacteurRisque',
        ),
        migrations.DeleteModel(
            name='StatCancerCommune',
        ),
        migrations.DeleteModel(
            name='StatCancerWilaya',
        ),
        migrations.DeleteModel(
            name='Wilaya',
        ),
    ]
