# Generated by Django 4.2.9 on 2026-03-25 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_nom_jeune_fille_patient_num_matricule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('biologie', 'Bilan biologique'), ('imagerie', 'Imagerie'), ('anapath', 'Anatomopathologie'), ('endoscopie', 'Endoscopie'), ('cardiologie', 'Cardiologie')], max_length=50)),
                ('nom_examen', models.CharField(max_length=200)),
                ('date_prescription', models.DateField()),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('resultat', models.TextField(blank=True)),
                ('fichier_dicom', models.FileField(blank=True, null=True, upload_to='examens/dicom/')),
                ('statut', models.CharField(choices=[('prescrit', 'Prescrit'), ('en_attente', 'En attente'), ('realise', 'Réalisé'), ('annule', 'Annulé')], default='prescrit', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_medicaux', to='patients.patient')),
                ('prescrit_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_prescrits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen Médical',
                'verbose_name_plural': 'Examens Médicaux',
                'db_table': 'examen_medical',
                'ordering': ['-date_prescription'],
            },
        ),
    ]
